#ifndef TETROMINO_HPP

#define TETROMINO_HPP
#define NUM_TETROMINOS 7

enum { TETROMINO_NONE, TETROMINO_SQUARE, TETROMINO_STRAIGHT, 
       TETROMINO_SKEW_A, TETROMINO_SKEW_B, TETROMINO_L_A,
       TETROMINO_L_B, TETROMINO_T }; //TetrominoTypes;

enum { MOVE_NONE, MOVE_LEFT, MOVE_RIGHT, MOVE_DOWN,
       MOVE_ROTATE, MOVE_PAUSE }; //MoveDirs;

class Tetromino;

#endif

